language: node_js
sudo: required
node_js: 10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install -g bower
  - bower install
  - npm install
script:
  - travis_wait pulp build
  - travis_wait make run-example
  - travis_wait pulp test

cache:
  directories:
    - output
